# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

variables:
  isReleaseTag: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: 
  fetchDepth: 1

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'
    arguments: '-c ${buildConfiguration}'

- task: DotNetCoreCLI@2
  displayName: Unit Test
  inputs:
    command: 'test'
    projects: '**/*.Tests/*.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Packaging
  inputs:
    command: 'pack'
    projects: 'src/**/*.csproj'
    versioningScheme: 'off'
  condition: and(succeeded(), eq(variables['isReleaseTag'], 'true'))
