name: .NET Core

on:
  push:
    tags:
      - v*
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        id: tag_name
        if: ${{ contains(github.ref, 'tags/v') }}
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/v}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.807
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        run: dotnet restore --use-lock-file --locked-mode
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        if: ${{ !contains(github.ref, 'tags/v') }}
        run: dotnet test -f netcoreapp2.1 --no-restore --no-build
      - name: Pack for dev
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          dotnet pack --no-build --no-restore -o publish -p:PackageVersion=${GITHUB_SHA}
  publish:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'tags/v') }}
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        id: tag_name
        if: ${{ contains(github.ref, 'tags/v') }}
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/v}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.807
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        run: dotnet restore --use-lock-file --locked-mode
      - name: Pack
        run: dotnet pack -c Release --no-build --no-restore -o publish -p:PackageVersion=${{steps.tag_name.outputs.SOURCE_TAG}}
      - name: Publish
        env:
          API_KEY: ${{ secrets.NUGET_API_EKY }}
        run: |
          dotnet nuget push "publish/StringExtension.${{steps.tag_name.outputs.SOURCE_TAG}}.nupkg" -k "$API_KEY" -s https://api.nuget.org/v3/index.json
